### ISSUE TITLE
Consider moving the repo to a different organization

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/perprof-py#207]
We moved it from https://github.com/lpoo to https://github.com/ufpr-opt because none of us were at UNICAMP and Abel was at UFPR. Now, Abel is not at UFPR and I don't know he signed a collaboration agreement or not.

We could keep the project under Abel's account or create a independent organisation or join one existing organisation (e.g. [pyOpenSci](https://www.pyopensci.org/python-packages/))

_Originally posted by @rgaiacs in https://github.com/ufpr-opt/perprof-py/pull/204#discussion_r949710663_

**Comment by abelsiqueira** [comment]
cc. @lrsantos11

**Comment by abelsiqueira** [comment]
I would like to move as well. In the end, nobody at UFPR adopted this repo, so we can, in principle, do whatever we want.
That being said, since this is used in the publication, it would be ideal if we could keep either a mirror or a redirect here.

From the given options, I would not mind creating a new organization or keeping the repo in my account. Since we don't have a strong community, I'd rather not try moving to an existing organization yet.

**Comment by rgaiacs** [comment]
> That being said, since this is used in the publication, it would be ideal if we could keep either a mirror or a redirect here.

I thought that we had used https://github.com/lpoo in the article. My memory is cloudy of when Abel started at UFPR and the time that we started writing given that we presented it in Florianópolis.

If you transfer the project between users, GitHub will redirect.

My recommendation is

1. Fork it to a new account.
2. Add a note in the README about moving to a new address.
3. Update the metadata information in the repository.
4. Archive the project.

**Comment by lrsantos11** [comment]
I agree with @rgaiacs here. The ideia of @abelsiqueira to make the link to the new repo is intersting too. 
BTW, other than the paper, are people citing this repo also @abelsiqueira ? If this is the case, it is not counting on agregating tools like Google Scholar. Do you know if it is possible?

**Comment by abelsiqueira** [comment]
We moved from lpoo before publishing.
I don't know if they are citing this repo, because I only get notifications from citation that go through research gate.

I will transfer the repo and leave this as fork.

**Comment by abelsiqueira** [comment]
I just read that it is always redirected: https://github.com/orgs/community/discussions/22669
Maybe we just leave it? It's one less step, but it might be more confusing.

**Comment by abelsiqueira** [comment]
After 6 months it still redirects, so I'm keeping it here.
